### ISSUE TITLE
Login is not working any longer

### ISSUE THREAD

**Issue by Software-Design** [eyecatchup/php-webmaster-tools-downloads#4]
I now get "HTTP 403 Forbidden" when I try to login to the webmaster tools using this API  library. Login information is correct and there is no further description of the occurred error.

**Comment by Software-Design** [comment]
It seems as if there was a problem with the authentification by Google - the script is now working again

**Comment by jeremywadsack** [comment]
We get this error all the time. Usually for about 15% of our download requests. I believe it's related to some kind of rate limiting, because when it starts happening it continues to happen until we throttle down the requests at which case the 403's reduce in a decay over time.

As near as I can tell this is coming from the sign-in service, not from the download feed itself. Using multiple servers doesn't seem to address this (so it's not an IP issue).

**Comment by vincentkoc** [comment]
Use a 2-Factor Authentication on the Google Account and sign-in using the "application password", and say no more to 403's :D - I have a few patches ive done which ill do a pull request for.

**Comment by jeremywadsack** [comment]
@koconder that's great! I'll give that a shot. 

We forked this about three years ago and have made so many changes I'm afraid to merge, but I'll work on it and open PR's for anything that might be useful.

**Comment by jeremywadsack** [comment]
@koconder Thank you for this suggestion. It fixed out login problems perfectly.

**Comment by vincentkoc** [comment]
@eyecatchup let me know if i can have contributor so i can update documents - this ticket can now be closed!

**Comment by jeremywadsack** [comment]
@koconder It turns out we still get this. A lot less than we used to (like 0.25% of requests yesterday, 0.33% the day before; vs. 15% before we made the switch), but we still get a few every day. We just doubled our request speed and that increased the failure rate to 11%.

So switching to 2-factor authentication reduced the error rate but it doesn't allow us to increase our request rate. 

How did you discover this? Is it documented somewhere? I can't seem to find anything that states any limits related to use of the ClientLogin service.
